inherit_from:
  - .rubocop_airbnb.yml

LineLength:
  Max: 120

AllCops:
  # ファイルの初期状態・自動生成状態で違反するもの、rubocopに従わない方がコードが読みやすくなるものが除外対象
  Exclude:
    - bin/*
    - config/environments/*
    - config/initializers/cors.rb
    - config/initializers/devise.rb
    - config/application.rb
    - spec/spec_helper.rb
    - db/schema.rb