inherit_from:
  - .rubocop_airbnb.yml

LineLength:
  Max: 120

AllCops:
  Exclude:
    - bin/*
    - config/environments/*
    - config/initializers/cors.rb
    - config/application.rb
    - spec/spec_helper.rb