inherit_from:
  - .rubocop_airbnb.yml

LineLength:
  Max: 120

AllCops:
  # ファイルの初期状態で1行の文字数制限を超えるもの、rubocopに従わない方がコードが読みやすくなるものが除外対象
  Exclude:
    - bin/*
    - config/environments/*
    - config/initializers/cors.rb
    - config/application.rb
    - spec/spec_helper.rb