version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - setup
  test:
    docker:
      - image: circleci/ruby:2.7.3
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: rspec
          command: bundle exec rspec

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build

