version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3
  aws-ecr: circleci/aws-ecr@7.2.0
  # heroku: circleci/heroku@1.2.6

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    steps:
      - setup

  test:
    docker:
      - image: circleci/ruby:2.7.3
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: password
          TZ: "Asia/Tokyo"
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: test
      TZ: "Asia/Tokyo"
    steps:
      - setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

  build_and_push_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "lsdb-api"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./api/
          profile-name: AWS_USER_NAME

  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - checkout
  #     - heroku/install
  #     - heroku/deploy-via-git

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
      - build_and_push_image:
          requires:
            - test

